name: CI/CD Pipeline
on: [push]
jobs:
  build_and_test_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install joblib scikit-learn
      - name: Run training script
        run: python train.py
      - name: Build Docker image
        run: docker build -t yourusername/mlops_model .
      - name: Test Docker image
        run: docker run yourusername/mlops_model
      - name: Push to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push yourusername/mlops_model